spring.application.name=chatify


##sprig data jpa
spring.datasource.url=jdbc:postgresql://localhost:5432/chatify-db
spring.datasource.username=madlx
spring.datasource.password=28268452
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


